main: com.cinemamod.bukkit.CinemaModPlugin
name: CinemaMod
version: 1.0.7
api-version: 1.21
author: ds58
depend: [ WorldGuard, ProtocolLib ]
commands:
  request:
    description: Request a video to be added to a theater queue
    aliases: [ rq ]
  forceskip:
    description: Force skip a video
  voteskip:
    description: Vote skip a video
  lockqueue:
    description: Lock the video queue for your theater
  volume:
    description: Set the volume for videos
  playing:
    description: Show information about what's playing
  history:
    description: Show your previously requested videos
